### PR TITLE
MNT: account for CPython 314 changes

### PR DESCRIPTION
**Pull request by tacaswell**
https://github.com/python/cpython/pull/125251 renamed _PY_IMMORTAL_REFCNT -> _PY_IMMORTAL_INITIAL_REFCNT

### CODE REVIEW

**Comment by tacaswell** [comment]
fair enough, but I would go with the new name rather than the old one (I think the new one is clearer).

**Comment by tacaswell** [comment]
(sorry, could not keep my bikeshedding comments to my self).

**Comment by jcrist** [comment]
Fair enough! Out of curiousity - are you using Python dev w/ msgspec for something? How did you find this compatibility issue?

**Review by jcrist — APPROVED** [review]

**Comment by tacaswell** [comment]
I have a project that tries to build the development branch of everything (https://github.com/tacaswell/build_the_world) with the goal of catching these things as early as possible.  I then try to work in that environment for my day-to-day development.  I was playing with msgspec a while ago so it ended up in my build list.

**Comment by ofek** [comment]
Really great find, thanks!

**Pull request merged**
