### PR TITLE
Compare to pydantic v2

### PR DESCRIPTION
**Pull request by Olegt0rr**
Relates to #523 

Also need to
- [ ] Update results

Also would be great to add both pydantic version comparison.

My results:
```
Benchmark - 1000 objects with validation

msgspec
  dumps: 126.68 us
  loads: 324.15 us
  total: 450.83 us

pydantic
  dumps: 2478.84 us
  loads: 1886.44 us
  total: 4365.29 us

cattrs
  dumps: 2025.52 us
  loads: 2365.95 us
  total: 4391.47 us

mashumaro
  dumps: 785.82 us
  loads: 1392.68 us
  total: 2178.51 us
```

pip freeze
```
annotated-types==0.5.0
attrs==23.1.0
cattrs==23.1.2
certifi==2023.7.22
charset-normalizer==3.2.0
idna==3.4
mashumaro==3.9
msgpack==1.0.5
-e git+https://github.com/Olegt0rr/msgspec.git@0041a67b77ee91286b5e76b6529ee3e32f66df6b#egg=msgspec
orjson==3.9.5
pydantic==2.1.1
pydantic_core==2.4.0
requests==2.31.0
typing_extensions==4.7.1
ujson==5.8.0
urllib3==2.0.4
```

### CODE REVIEW

**Comment by akotlar** [comment]
Impressive advantage for msgspec vs pydantic v2

**Comment by ofek** [comment]
cc @samuelcolvin

**Comment by LockedThread** [comment]
@Olegt0rr Can you send the link to your benchmark repo? I would like to implement [ormsgpack](https://github.com/aviramha/ormsgpack) benchmarks. See #608.

**Comment by jcrist** [comment]
Thanks for the PR and apologies for the delay here, I haven't had as much time as usual to devote to OSS activities lately. I've pushed an extra commit to this PR that does a major overhaul to the benchmarks. A brief summary:

- Benchmark against Pydantic V2 instead of V1
- Adds a few additional JSON and MessagePack libraries
- Documents the versions of libraries used for each run
- Bumps the python version used from 3.9 to 3.11. This made several of the pure-python libraries compared measurably faster. Yay for the faster CPython initiative.

**Pull request merged**
